### ISSUE TITLE
Crashing the program due to Missing frontend.utils module

### ISSUE THREAD

**Issue by tudopropaganda** [GabeGiro/EasyApplyJobsBot#70]
In the file repository_wrapper.py
I have this missing import statement in line 21.

`from frontend.utils import (
            api as backend_api,  # Change this line with your backend module
        )`

**repository_wrapper.py**
![image](https://github.com/user-attachments/assets/1326ed08-44c7-473e-8f0a-6e796e6c8671)

I see there is no frontend dir in the repo. 

The program is exiting prematurely:
![image](https://github.com/user-attachments/assets/f3d7b7b8-ebe6-4de1-a719-1b8a9d43e543)

I'm trying to run it locally, without Docker.

Please, can you check?

**Comment by GabeGiro** [comment]
@tudopropaganda please checkout the created PR which by default displays error messages now and am curious if it gives you any different output now.

I removed the .env file to test it and on my machine, it runs. 

The main advantage of using Docker: there is no ambiguity about different setups two of us might have... I'll leave it up to you to propose a solution inside the already existing PR, otherwise, I'll close the issue in a week or two.

Thank you for your effort either way 🙏

**Comment by GabeGiro** [comment]
P.S. the backend / frontend setup is for you to create if you want. Otherwise just ignore it. I have that repository_wrapper for my project that I'm working on.

**Comment by GabeGiro** [comment]
@tudopropaganda great that it works! I'll close this issue then.

The message "Extra info needed..." could be replaced with "Answers to some questions missing" which is more specific. Currently, answering questions is not done but the tasks that are related to it are under the following milestone https://github.com/GabeGiro/EasyApplyJobsBot/milestone/1
Fair results are there for very easy applications which don't need any additional questions answered. But, I agree that answering should be done as part of this repo. The original repo might have some clues to how to answer to questions but I think the original contributor made it a paid feature if I remember correctly...not sure.

As far as the repository_wrapper goes, I agree that it might be misleading and I will think about a better solution so that it's not part of the public repo.

I'll check your PR asap. Thank you 🙏
